/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PIT0.h
**     Project     : HBLLC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_PIT
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-27, 11:59, # CodeGen: 0
**     Abstract    :
**          This file implements the PIT (PIT0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PIT0
**          Device                                         : PIT0
**          Settings                                       : 
**            Select master                                : Master 0 and slave 1
**            Slave mode                                   : Disabled
**            Clock settings                               : 
**              Clock select                               : BUS_CLK
**              Prescaler                                  : divide by 1
**              Counter frequency                          : 50 MHz
**              Modulo register                            : 50000
**              Period                                     : 1 ms
**          Interrupts                                     : 
**            Roll-over                                    : 
**              Interrupt                                  : INT_PIT0_ROLLOVR
**              Interrupt priority                         : 0
**              ISR Name                                   : PIT0_ISR
**              Roll-over interrupt                        : Enabled
**          Initialization                                 : 
**            Enable peripheral clock                      : yes
**            Enable timer                                 : no
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void PIT0_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PIT0.h
** @version 01.00
** @brief
**          This file implements the PIT (PIT0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup PIT0_module PIT0 module documentation
**  @{
*/         

#ifndef PIT0_H_
#define PIT0_H_

/* MODULE PIT0. */

#include "PIT0_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define PIT0_Init PIT0_Init
/* PDD macros peripheral base address parameter */
#define PIT0_DEVICE PIT0_BASE_PTR
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see PIT0.c file for more information).
** ===================================================================
*/
void PIT0_ISR(void);

#ifdef __cplusplus
}
#endif

/* END PIT0. */
#endif /* #ifndef __PIT0_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
