/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SIM.h
**     Project     : HBLLC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_SIM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-27, 11:59, # CodeGen: 0
**     Abstract    :
**          This file implements the SIM (SIM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : SIM
**          Device                                         : SIM
**          Common CPU settings                            : 
**            WAIT disable mode                            : Enabled
**            STOP disable mode                            : Enabled
**            DMA disable mode                             : All modes
**            OnCE clock to core                           : Enabled when core TAP is enabled
**            Reset filter                                 : Disabled
**            CLKIN input                                  : GPIOC0
**            Select master PIT                            : Master 0 and slave 1
**            ADC scan control bits re-ordering            : Disabled
**            Dual speed core clock                        : Enabled
**          Power controls                                 : 
**            Regulator 1.2 V standby                      : normal mode
**            Regulator 2.7 V powerdown                    : normal mode
**            Regulator 2.7 V standby                      : normal mode
**            Large regulator standby                      : normal mode
**            LPMODE                                       : Exit
**            VLPMODE                                      : Exit
**          Clock output selectors                         : 
**            CLKOUT divide factor                         : Divide by 1
**            CLKOUT0 select                               : System clock
**            CLKOUT0                                      : Disabled
**            CLKOUT1 select                               : System clock
**            CLKOUT1                                      : Disabled
**          Clock gating control in stop mode              : 
**            GPIOA peripheral clock in stop mode          : Disabled
**            GPIOB peripheral clock in stop mode          : Disabled
**            GPIOC peripheral clock in stop mode          : Disabled
**            GPIOD peripheral clock in stop mode          : Disabled
**            GPIOE peripheral clock in stop mode          : Disabled
**            GPIOF peripheral clock in stop mode          : Disabled
**            Timer channel 0 peripheral clock in stop mode : Disabled
**            Timer channel 1 peripheral clock in stop mode : Disabled
**            Timer channel 2 peripheral clock in stop mode : Disabled
**            Timer channel 3 peripheral clock in stop mode : Disabled
**            MSCAN peripheral clock in stop mode          : Disabled
**            I2C peripheral clock in stop mode            : Disabled
**            QSPI0 peripheral clock in stop mode          : Disabled
**            QSPI1 peripheral clock in stop mode          : Disabled
**            QSCI0 peripheral clock in stop mode          : Disabled
**            QSCI1 peripheral clock in stop mode          : Disabled
**            DACA peripheral clock in stop mode           : Disabled
**            DACB peripheral clock in stop mode           : Disabled
**            Programmable Interval Timer 0 peripheral clock in stop mode : Disabled
**            Programmable Interval Timer 1 peripheral clock in stop mode : Disabled
**            CRC peripheral clock in stop mode            : Disabled
**            Cyclic ADC peripheral clock in stop mode     : Disabled
**            CMPA peripheral clock in stop mode           : Disabled
**            CMPB peripheral clock in stop mode           : Disabled
**            CMPC peripheral clock in stop mode           : Disabled
**            CMPD peripheral clock in stop mode           : Disabled
**            PWMA channel 0 peripheral clock in stop mode : Disabled
**            PWMA channel 1 peripheral clock in stop mode : Disabled
**            PWMA channel 2 peripheral clock in stop mode : Disabled
**            PWMA channel 3 peripheral clock in stop mode : Disabled
**          Clock gating control                           : 
**            GPIOA peripheral clock                       : Disabled
**            GPIOB peripheral clock                       : Disabled
**            GPIOC peripheral clock                       : Enabled
**            GPIOD peripheral clock                       : Disabled
**            GPIOE peripheral clock                       : Disabled
**            GPIOF peripheral clock                       : Enabled
**            Timer channel 0 peripheral clock             : Disabled
**            Timer channel 1 peripheral clock             : Disabled
**            Timer channel 2 peripheral clock             : Disabled
**            Timer channel 3 peripheral clock             : Disabled
**            MSCAN peripheral clock                       : Disabled
**            I2C peripheral clock                         : Disabled
**            QSPI0 peripheral clock                       : Disabled
**            QSPI1 peripheral clock                       : Disabled
**            QSCI0 peripheral clock                       : Enabled
**            QSCI1 peripheral clock                       : Enabled
**            DACA peripheral clock                        : Disabled
**            DACB peripheral clock                        : Disabled
**            Programmable Interval Timer 0 peripheral clock : Enabled
**            Programmable Interval Timer 1 peripheral clock : Disabled
**            CRC peripheral clock                         : Disabled
**            Cyclic ADC peripheral clock                  : Enabled
**            CMPA peripheral clock                        : Enabled
**            CMPB peripheral clock                        : Enabled
**            CMPC peripheral clock                        : Disabled
**            CMPD peripheral clock                        : Enabled
**            PWMA channel 0 peripheral clock              : Enabled
**            PWMA channel 1 peripheral clock              : Enabled
**            PWMA channel 2 peripheral clock              : Enabled
**            PWMA channel 3 peripheral clock              : Disabled
**          Peripheral clock rate                          : 
**            QSCI0 clock rate                             : Bus clock
**            QSCI1 clock rate                             : Bus clock
**            TMR clock rate                               : Bus clock
**            PWM clock rate                               : 2X bus clock
**            I2C filter clock rate                        : Bus clock
**          Peripheral protection                          : 
**            Power mode control write                     : Off
**            GPIO port D                                  : Off
**            Peripheral clock enable                      : Off
**            GPIO and internal peripheral select          : Off
**          Peripheral select                              : 
**            GPIOA0 pin function                          : ANA0_CMPA_IN3
**            GPIOB1 pin function                          : ANB1_CMPB_IN0
**            GPIOC0 pin function                          : EXTAL
**            GPIOC2 pin function                          : TXD0
**            GPIOC3 pin function                          : RXD0
**            GPIOC4 pin function                          : TA1
**            GPIOC5 pin function                          : DACA_O
**            GPIOC6 pin function                          : TA2
**            GPIOC7 pin function                          : SS0_B
**            GPIOC8 pin function                          : MISO0
**            GPIOC9 pin function                          : SCK0
**            GPIOC10 pin function                         : MOSI0
**            GPIOC11 pin function                         : TXD1
**            GPIOC12 pin function                         : RXD1
**            GPIOC13 pin function                         : TA3
**            GPIOC14 pin function                         : alt0
**            GPIOC15 pin function                         : SCL0
**            GPIOE4 pin function                          : PWM_2B
**            GPIOE5 pin function                          : PWM_2A
**            GPIOE6 pin function                          : PWM_3B
**            GPIOE7 pin function                          : PWM_3A
**            GPIOF0 pin function                          : XB_IN6
**            GPIOF1 pin function                          : CLKO1
**            GPIOF2 pin function                          : XB_OUT6
**            GPIOF3 pin function                          : XB_OUT7
**            GPIOF4 pin function                          : XB_OUT8
**            GPIOF5 pin function                          : XB_OUT9
**            GPIOF6 pin function                          : NotConnected
**            GPIOF7 pin function                          : NotConnected
**            GPIOF8 pin function                          : PWM_2X
**          Internal peripheral select                     : 
**            SCI0 input                                   : GPIOC3_GPIOC8_GPIOF8
**            SCI1 input                                   : GPIOC12_GPIOF5
**            TA0 input                                    : GPIOC3
**            TA1 input                                    : GPIOC4
**            TA2 input                                    : GPIOC6
**            TA3 input                                    : GPIOC13
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void SIM_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SIM.h
** @version 01.00
** @brief
**          This file implements the SIM (SIM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup SIM_module SIM module documentation
**  @{
*/         

#ifndef SIM_H_
#define SIM_H_

/* MODULE SIM. */

#include "SIM_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define SIM_Init SIM_Init
/* PDD macros peripheral base address parameter */
#define SIM_DEVICE SIM_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END SIM. */
#endif /* #ifndef __SIM_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
